### ISSUE TITLE
tests intermittently time out during Scala community build

### ISSUE THREAD

**Issue by SethTisue** [typelevel/scalacheck#358]
I know I've seen this several times before but I don't think I've reported it: 

```
[scalacheck] [info] + Commands.commands: OK, passed 100 tests.
Warning: system did not shut down within the allotted time
An exception occurred.
akka.pattern.AskTimeoutException: Timed out
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:312)
	at akka.actor.DefaultScheduler$$anon$8.run(Scheduler.scala:191)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:137)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

(from https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2005/consoleFull)

**Comment by SethTisue** [comment]
haven't seen this in ages that I can recall
