### ISSUE TITLE
scalacheck_sjs0.6_2.12 1.14.1-RC1 broken

### ISSUE THREAD

**Issue by xuwei-k** [typelevel/scalacheck#536]
https://travis-ci.org/xuwei-k/scalaz/jobs/585078615#L511

```
[error] org.scalajs.core.ir.IRVersionNotSupportedException: Failed to deserialize info of file compiled with Scala.js 1.0.0-M8 (supported: 0.6.0, 0.6.13, 0.6.3, 0.6.17, 0.6.4, 0.6.6, 0.6.14, 0.6.8, 0.6.5, 0.6.15): /home/travis/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalacheck/scalacheck_sjs0.6_2.12/1.14.1-RC1/scalacheck_sjs0.6_2.12-1.14.1-RC1.jar:org/scalacheck/GenArities$$anon$78$$anon$79$$anon$80$$anon$81$$anon$82$$anon$83$$anon$84$$anon$85$$anon$86$$anon$87.sjsir
[error] 	at org.scalajs.core.tools.io.VirtualSerializedScalaJSIRFile.info(VirtualFiles.scala:165)
[error] 	at org.scalajs.core.tools.io.VirtualSerializedScalaJSIRFile.info$(VirtualFiles.scala:156)
[error] 	at org.scalajs.core.tools.io.MemVirtualSerializedScalaJSIRFile.info(MemFiles.scala:107)
[error] 	at org.scalajs.core.tools.io.IRFileCache$PersistentIRFile.<init>(IRFileCache.scala:247)
[error] 	at org.scalajs.core.tools.io.IRFileCache$PersistedFiles.$anonfun$update$5(IRFileCache.scala:222)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at scala.collection.immutable.List.map(List.scala:298)
[error] 	at org.scalajs.core.tools.io.IRFileCache$PersistedFiles.update(IRFileCache.scala:222)
[error] 	at org.scalajs.core.tools.io.IRFileCache$Cache.$anonfun$update$2(IRFileCache.scala:100)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at org.scalajs.core.tools.io.IRFileCache$Cache.$anonfun$update$1(IRFileCache.scala:87)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at org.scalajs.core.tools.io.IRFileCache.org$scalajs$core$tools$io$IRFileCache$$clearOnThrow(IRFileCache.scala:283)
[error] 	at org.scalajs.core.tools.io.IRFileCache$Cache.update(IRFileCache.scala:84)
[error] 	at org.scalajs.core.tools.io.IRFileCache$Cache.cached(IRFileCache.scala:80)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$10(ScalaJSPluginInternal.scala:493)
[error] 	at sbt.internal.util.Attributed.map(Attributes.scala:262)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$7(ScalaJSPluginInternal.scala:493)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by non** [comment]
Thanks for catching this!

The procudure I used to publish that release was:

```
SCALAJS_VERSION="0.6.28" sbt "+ js/publishSigned"
```

Since the version published was tagged with `sjs0.6` it seems like SBT must have thought I was using the right plugin. I'm not sure how this happened but I'm looking into it now using `publishLocal`.

**Comment by non** [comment]
OK, I figured the issue out. Apparently I need to manually `clean` when changing versions of ScalaJS (and possibly Scala Native). Otherwise I'll end up publishing stale artifacts compiled with the wrong version of ScalaJS.

I'm going to publish RC2, which hopefully won't have this issue.

**Comment by non** [comment]
I just released 1.14.1-RC2 which should be fixed. I tested locally (using `publishLocal`) and was able to load versions for both 0.6.28 and 1.0.0-M8. Please let me know if this version works for you or if you still have problems. Thanks again for reporting this issue.

**Comment by non** [comment]
@xuwei-k It seems like RC2 is OK, does it work for you?

**Comment by xuwei-k** [comment]
🙆‍♂
