### ISSUE TITLE
Invalid bounds in JavaTimeChoose

### ISSUE THREAD

**Issue by sangamon** [typelevel/scalacheck#762]
Version: 1.15.3

Caused by: org.scalacheck.Gen$Choose$IllegalBoundsError: invalid bounds: low=1, high=0
	at org.scalacheck.Gen$Choose$$anon$8.choose(Gen.scala:475)
	at org.scalacheck.Gen$Choose$$anon$8.choose(Gen.scala:473)
	at org.scalacheck.Gen$Choose$$anon$12.choose(Gen.scala:596)
	at org.scalacheck.Gen$.choose(Gen.scala:637)
	at org.scalacheck.time.JavaTimeChoose$$anon$2.$anonfun$choose$3(JavaTimeChoose.scala:68)
	at org.scalacheck.time.JavaTimeChoose$$anon$2.$anonfun$choose$3$adapted(JavaTimeChoose.scala:55)

Looks like the case where, in #chooseInstant, epochSecond != min.getEpochSecond and epochSecond == max.getEpochSecond == 0.

**Comment by sangamon** [comment]
Example (from a debug run):
- min = "2025-10-06T06:52:06Z"
- max = "2025-10-06T07:23:11Z"
- min.getEpochSecond = 1759733526
- max.getEpochSecond = 1759735391
- epochSecond: 1759735391
- minNano = 1
- maxNano = 0
